

; ---------------------------------------------------------------------------

; enum Traps
SOUND_COMMAND: equ $0

; ---------------------------------------------------------------------------

; enum SoundCommands
SOUND_COMMAND_INIT_DRIVER: equ $20
SOUND_COMMAND_WAIT_MUSIC_END: equ $F0
SOUND_COMMAND_PLAY_PREVIOUS_MUSIC: equ $FB
SOUND_COMMAND_FADE_OUT: equ $FD
SOUND_COMMAND_STOP_MUSIC: equ $FE
SOUND_COMMAND_FFFADE_OUT: equ $FFFD
SOUND_COMMAND_GET_D0_PARAMETER: equ $FFFF

; ---------------------------------------------------------------------------

; enum Music
MUSIC_NOTHING: equ $0
MUSIC_BUSTLING_STREET: equ $1
MUSIC_TORCHLIGHT: equ $2
MUSIC_PREMONITION_OF_TROUBLE: equ $3
MUSIC_JINGLE_3: equ $4
MUSIC_ITEM_CHEST: equ $5
MUSIC_REST: equ $6
MUSIC_SAVE: equ $7
MUSIC_CURE: equ $8
MUSIC_POISON: equ $9
MUSIC_THE_DEATH_GODS_INVITATION: equ $A
MUSIC_JINGLE_2: equ $B
MUSIC_JINGLE_1: equ $C
MUSIC_WHISTLE: equ $D
MUSIC_BLACK_MARKET: equ $E
MUSIC_DRAMATIC_EFFECT: equ $F
MUSIC_TITLE_SCREEN: equ $10
MUSIC_LETS_GO_ON_AN_ADVENTURE: equ $11
MUSIC_TREASURE_HUNTER_NIGEL: equ $12
MUSIC_SEEKING_TREASURE: equ $13
MUSIC_DESERTED_STREET_CORNER: equ $14
MUSIC_FRIDAY_AND_A_SOFT_BREEZE: equ $15
MUSIC_HEY_ITS_YOUR_TURN: equ $16
MUSIC_17_VOID: equ $17
MUSIC_18_VOID: equ $18
MUSIC_19_VOID: equ $19
MUSIC_1A_VOID: equ $1A
MUSIC_TO_THE_GREAT_ADVENTURERS: equ $1B
MUSIC_1C_VOID: equ $1C
MUSIC_BENEATH_THE_MYSTERIOUS_TREE: equ $1D
MUSIC_1E_VOID: equ $1E
MUSIC_URGENT_NIGEL: equ $1F
MUSIC_STOP: equ $20
MUSIC_PRAYERS_TO_GOD: equ $21
MUSIC_LIGHT_OF_THE_SETTING_SUN: equ $22
MUSIC_WICKED_GODS_BANQUET: equ $23
MUSIC_HEHEH_THINK_ILL_DISRUPT_THIS_GOOD_CHEER: equ $24
MUSIC_THE_MARQUIS_INVITATION: equ $25
MUSIC_THE_KINGS_CHAMBER: equ $26
MUSIC_MYSTERIOUS_ISLAND: equ $27
MUSIC_FRIDAYS_MEMORY: equ $28
MUSIC_DIVINE_GUARDIAN_OF_THE_MAZE: equ $29
MUSIC_THE_SILENCE_THE_DARKNESS_AND: equ $2A
MUSIC_LABYRINTH: equ $2B
MUSIC_A_BALLAD_FOR_PRINCESS_LORIA: equ $2C
MUSIC_A_BALLAD_FOR_PRINCESS_LORIA_LOOP: equ $2D
MUSIC_PINK_BOOK: equ $2E
MUSIC_ADVENTURE_SPIRIT: equ $2F

; ---------------------------------------------------------------------------

; enum Sfx
SFX_MENU_SWITCH: equ $41
SFX_MENU_SELECTION: equ $42
SFX_VALIDATION: equ $43
SFX_REFUSAL: equ $44
SFX_DIALOG_BLEEP_1: equ $45
SFX_DIALOG_BLEEP_2: equ $46
SFX_DIALOG_BLEEP_3: equ $47
SFX_DIALOG_BLEEP_4: equ $48
SFX_DIALOG_BLEEP_5: equ $49
SFX_DIALOG_BLEEP_6: equ $4A
SFX_DIALOG_BLEEP_7: equ $4B
SFX_DIALOG_BLEEP_8: equ $4C
SFX_SPELL_CAST: equ $4D
SFX_DRUM: equ $4E
SFX_CYMBAL: equ $4F
SFX_SNARE: equ $50
SFX_SWORD_SLASH: equ $51
SFX_SWORD_CLANG: equ $52
SFX_JUMP: equ $53
SFX_FALL: equ $54
SFX_WARP_STEPS: equ $55
SFX_BLOB: equ $56
SFX_WING_FLAP: equ $57
SFX_BOULDER_HIT: equ $58
SFX_RUMBLE: equ $59
SFX_SPECIAL_ITEM_USE: equ $5A
SFX_MONSTER_SKREECH: equ $5B
SFX_BUBOBI: equ $5C
SFX_STEP: equ $5D
SFX_DOUBLE_STEP: equ $5E
SFX_BLIP: equ $5F
SFX_BLO: equ $60
SFX_EKE: equ $61
SFX_ITEM_DROP: equ $62
SFX_ITEM_DROP_HIGHER_PITCH: equ $63
SFX_EKE_LOWER_PITCH: equ $64
SFX_DEATH: equ $65
SFX_ENEMY_DEATH: equ $66
SFX_ENEMY_HIT: equ $67
SFX_ITEM_SELECT: equ $68
SFX_ITEM_USE: equ $69
SFX_HEALTH_RESTORE: equ $6A
SFX_TECH_1: equ $6B
SFX_SWITCH: equ $6C
SFX_EXPLOSION: equ $6D
SFX_TRAP_HIT: equ $6E
SFX_ENEMY_DEATH_LOWER_PITCH: equ $6F
SFX_ENEMY_HIT_LOWER_PITCH: equ $70
SFX_SHLARF: equ $71
SFX_SHLARF_LOWER_PITCH: equ $72
SFX_SHORT_RUMBLE: equ $73
SFX_SWITCH_TRIGGER: equ $74
SFX_BIG_STEP: equ $75
SFX_FRIDAY_REVIVE: equ $76
SFX_ENEMY_SLASH: equ $77
SFX_SLASH: equ $78
SFX_TELEPORT: equ $79
SFX_POISON: equ $7A
SFX_NONE: equ $7F