

; ---------------------------------------------------------------------------

; enum Traps
SOUND_COMMAND: equ $0

; ---------------------------------------------------------------------------

; enum InterruptParametersBitmap
VDP_COMMAND_REQUEST: equ $0
DEACTIVATE_DMA: equ $1
DMA_REQUEST: equ $3
VRAM_READ_REQUEST: equ $4
ENABLE_INT: equ $7

; ---------------------------------------------------------------------------

; enum InputBitmap
INPUT_UP: equ $0
INPUT_DOWN: equ $1
INPUT_LEFT: equ $2
INPUT_RIGHT: equ $3
INPUT_B: equ $4
INPUT_C: equ $5
INPUT_A: equ $6
INPUT_START: equ $7

; ---------------------------------------------------------------------------

; enum SoundCommands
SOUND_COMMAND_INIT_DRIVER: equ $20
SOUND_COMMAND_WAIT_MUSIC_END: equ $F0
SOUND_COMMAND_PLAY_PREVIOUS_MUSIC: equ $FB
SOUND_COMMAND_FADE_OUT: equ $FD
SOUND_COMMAND_STOP_MUSIC: equ $FE
SOUND_COMMAND_FFFADE_OUT: equ $FFFD
SOUND_COMMAND_GET_D0_PARAMETER: equ $FFFF

; ---------------------------------------------------------------------------

; enum Music
MUSIC_NOTHING: equ $0
MUSIC_BUSTLING_STREET: equ $1
MUSIC_TORCHLIGHT: equ $2
MUSIC_PREMONITION_OF_TROUBLE: equ $3
MUSIC_JINGLE_3: equ $4
MUSIC_ITEM_CHEST: equ $5
MUSIC_REST: equ $6
MUSIC_SAVE: equ $7
MUSIC_CURE: equ $8
MUSIC_POISON: equ $9
MUSIC_THE_DEATH_GODS_INVITATION: equ $A
MUSIC_JINGLE_2: equ $B
MUSIC_JINGLE_1: equ $C
MUSIC_WHISTLE: equ $D
MUSIC_BLACK_MARKET: equ $E
MUSIC_DRAMATIC_EFFECT: equ $F
MUSIC_TITLE_SCREEN: equ $10
MUSIC_LETS_GO_ON_AN_ADVENTURE: equ $11
MUSIC_TREASURE_HUNTER_NIGEL: equ $12
MUSIC_SEEKING_TREASURE: equ $13
MUSIC_DESERTED_STREET_CORNER: equ $14
MUSIC_FRIDAY_AND_A_SOFT_BREEZE: equ $15
MUSIC_HEY_ITS_YOUR_TURN: equ $16
MUSIC_17_VOID: equ $17
MUSIC_18_VOID: equ $18
MUSIC_19_VOID: equ $19
MUSIC_1A_VOID: equ $1A
MUSIC_TO_THE_GREAT_ADVENTURERS: equ $1B
MUSIC_1C_VOID: equ $1C
MUSIC_BENEATH_THE_MYSTERIOUS_TREE: equ $1D
MUSIC_1E_VOID: equ $1E
MUSIC_URGENT_NIGEL: equ $1F
MUSIC_STOP: equ $20
MUSIC_PRAYERS_TO_GOD: equ $21
MUSIC_LIGHT_OF_THE_SETTING_SUN: equ $22
MUSIC_WICKED_GODS_BANQUET: equ $23
MUSIC_HEHEH_THINK_ILL_DISRUPT_THIS_GOOD_CHEER: equ $24
MUSIC_THE_MARQUIS_INVITATION: equ $25
MUSIC_THE_KINGS_CHAMBER: equ $26
MUSIC_MYSTERIOUS_ISLAND: equ $27
MUSIC_FRIDAYS_MEMORY: equ $28
MUSIC_DIVINE_GUARDIAN_OF_THE_MAZE: equ $29
MUSIC_THE_SILENCE_THE_DARKNESS_AND: equ $2A
MUSIC_LABYRINTH: equ $2B
MUSIC_A_BALLAD_FOR_PRINCESS_LORIA: equ $2C
MUSIC_A_BALLAD_FOR_PRINCESS_LORIA_LOOP: equ $2D
MUSIC_PINK_BOOK: equ $2E
MUSIC_ADVENTURE_SPIRIT: equ $2F

; ---------------------------------------------------------------------------

; enum Sfx
SFX_MENU_SWITCH: equ $41
SFX_MENU_SELECTION: equ $42
SFX_VALIDATION: equ $43
SFX_REFUSAL: equ $44
SFX_DIALOG_BLEEP_1: equ $45
SFX_DIALOG_BLEEP_2: equ $46
SFX_DIALOG_BLEEP_3: equ $47
SFX_DIALOG_BLEEP_4: equ $48
SFX_DIALOG_BLEEP_5: equ $49
SFX_DIALOG_BLEEP_6: equ $4A
SFX_DIALOG_BLEEP_7: equ $4B
SFX_DIALOG_BLEEP_8: equ $4C
SFX_SPELL_CAST: equ $4D
SFX_DRUM: equ $4E
SFX_CYMBAL: equ $4F
SFX_SNARE: equ $50
SFX_SWORD_SLASH: equ $51
SFX_SWORD_CLANG: equ $52
SFX_JUMP: equ $53
SFX_FALL: equ $54
SFX_WARP_STEPS: equ $55
SFX_BLOB: equ $56
SFX_WING_FLAP: equ $57
SFX_BOULDER_HIT: equ $58
SFX_RUMBLE: equ $59
SFX_SPECIAL_ITEM_USE: equ $5A
SFX_MONSTER_SKREECH: equ $5B
SFX_BUBOBI: equ $5C
SFX_STEP: equ $5D
SFX_DOUBLE_STEP: equ $5E
SFX_BLIP: equ $5F
SFX_BLO: equ $60
SFX_EKE: equ $61
SFX_ITEM_DROP: equ $62
SFX_ITEM_DROP_HIGHER_PITCH: equ $63
SFX_EKE_LOWER_PITCH: equ $64
SFX_DEATH: equ $65
SFX_ENEMY_DEATH: equ $66
SFX_ENEMY_HIT: equ $67
SFX_ITEM_SELECT: equ $68
SFX_ITEM_USE: equ $69
SFX_HEALTH_RESTORE: equ $6A
SFX_TECH_1: equ $6B
SFX_SWITCH: equ $6C
SFX_EXPLOSION: equ $6D
SFX_TRAP_HIT: equ $6E
SFX_ENEMY_DEATH_LOWER_PITCH: equ $6F
SFX_ENEMY_HIT_LOWER_PITCH: equ $70
SFX_SHLARF: equ $71
SFX_SHLARF_LOWER_PITCH: equ $72
SFX_SHORT_RUMBLE: equ $73
SFX_SWITCH_TRIGGER: equ $74
SFX_BIG_STEP: equ $75
SFX_FRIDAY_REVIVE: equ $76
SFX_ENEMY_SLASH: equ $77
SFX_SLASH: equ $78
SFX_TELEPORT: equ $79
SFX_POISON: equ $7A
SFX_NONE: equ $7F

; ---------------------------------------------------------------------------

; enum Item
ITEM_EKEEKE: equ $0
ITEM_MAGIC_SWORD: equ $1
ITEM_SWORD_OF_ICE: equ $2
ITEM_THUNDER_SWORD: equ $3
ITEM_SWORD_OF_GAIA: equ $4
ITEM_FIREPROOF: equ $5
ITEM_IRON_BOOTS: equ $6
ITEM_HEALING_BOOTS: equ $7
ITEM_SNOW_SPIKES: equ $8
ITEM_STEEL_BREAST: equ $9
ITEM_CHROME_BREAST: equ $A
ITEM_SHELL_BREAST: equ $B
ITEM_HYPER_BREAST: equ $C
ITEM_MARS_STONE: equ $D
ITEM_MOON_STONE: equ $E
ITEM_SATURN_STONE: equ $F
ITEM_VENUS_STONE: equ $10
ITEM_AWAKENING_BOOK: equ $11
ITEM_DETOX_GRASS: equ $12
ITEM_STATUE_OF_GAIA: equ $13
ITEM_GOLDEN_STATUE: equ $14
ITEM_MIND_REPAIR: equ $15
ITEM_CASINO_TICKET: equ $16
ITEM_AXE_MAGIC: equ $17
ITEM_BLUE_RIBBON: equ $18
ITEM_BUYER_CARD: equ $19
ITEM_LANTERN: equ $1A
ITEM_GARLIC: equ $1B
ITEM_ANTIPARALYZE: equ $1C
ITEM_STATUE_OF_JYPTA: equ $1D
ITEM_SUN_STONE: equ $1E
ITEM_ARMLET: equ $1F
ITEM_EINSTEIN_WHISTLE: equ $20
ITEM_DETOX_BOOK: equ $21
ITEM_ANTICURSE: equ $22
ITEM_RECORD_BOOK: equ $23
ITEM_SPELL_BOOK: equ $24
ITEM_HOTEL_REGISTER: equ $25
ITEM_ISLAND_MAP: equ $26
ITEM_LITHOGRAPH: equ $27
ITEM_RED_JEWEL: equ $28
ITEM_PAWN_TICKET: equ $29
ITEM_PURPLE_JEWEL: equ $2A
ITEM_GOLA_EYE: equ $2B
ITEM_DEATH_STATUE: equ $2C
ITEM_DAHL: equ $2D
ITEM_RESTORATION: equ $2E
ITEM_LOGS: equ $2F
ITEM_ORACLE_STONE: equ $30
ITEM_IDOL_STONE: equ $31
ITEM_KEY: equ $32
ITEM_SAFETY_PASS: equ $33
ITEM_NO52: equ $34
ITEM_BELL: equ $35
ITEM_SHORT_CAKE: equ $36
ITEM_GOLA_NAIL: equ $37
ITEM_GOLA_HORN: equ $38
ITEM_GOLA_FANG: equ $39
ITEM_5_GOLDS: equ $3A
ITEM_20_GOLDS: equ $3B
ITEM_50_GOLDS: equ $3C
ITEM_200_GOLDS: equ $3D
ITEM_LIFESTOCK: equ $3E
ITEM_EMPTY: equ $3F