name: Master-branch auto-propagation

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Auto merge on branch 'feature/romexpansion'
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'master'
        development_branch: 'feature/romexpansion'
        user_name: 'GitHub Auto Merge Action'  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
